### ISSUE TITLE
`w3up accounts` doesn't validate that there is a UCAN identity locally before running

### ISSUE THREAD

**Issue by dchoi27** [web3-storage/w3up-cli#109]
**Describe the bug**
On a fresh install, running `w3up accounts` throws this error:
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/11778450/193835470-8a37ffa4-6749-4443-b655-236d2e009168.png">

**To Reproduce**

1. Fresh install w3up on a computer
2. Run `w3up accounts`

**Expected behavior**
A message saying there are no accounts

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by olizilla** [comment]
similar issue when trying to upload with an unregistered id over here https://github.com/web3-storage/w3up-cli/issues/110
