### ISSUE TITLE
"no registered email" message should not show when using a delegated account.

### ISSUE THREAD

**Issue by yusefnapora** [web3-storage/w3up-cli#126]
I'm writing up the delegation walkthrough based on @alanshaw's hackmd [here](https://hackmd.io/@alanshaw/w3up-howto) and am at the final step of listing the uploads from the main account using the delegation. 

The second profile has imported the delegation and switched to the account, but when I run `w3up list --profile second`, I get a message saying `You have not setup an email, please run w3up register <email> first.`

**Expected behavior**

When I run `w3up list --profile second` after switching to the delegated main account, I should see the upload listing for the main account.

I would expect to still see the email registration message if the "self" account for the second profile is selected though.

**Desktop (please complete the following information):**

- OS: NixOS unstable
- Node: 18.9.1
- w3up: latest main branch

**Comment by alanshaw** [comment]
Is there something yusef is doing wrong @hugomrdias?

**Comment by yusefnapora** [comment]
Looks like Jeff beat me to it 😄 Dupe of #125
