### ISSUE TITLE
Unable to authenticate a new account using the CLI.

### ISSUE THREAD

**Issue by joshJarr** [web3-storage/w3up-cli#29]
Following the readme instruction, I've globally installed w3up and successfully generated an id using `w3up id`, the latest commit hash at the time of installing was `c5fe5df6f56c1908065b075d4fe3da52577168f3`.

The next step in the readme suggests running `w3up whoami`, this gives an error: `Could not check identity, check w3up-failure.log`.

When trying to register I also receive an error after following the email link:
```
 Error: Claimed capability {"can":"identity/register","with":"mailto:josh.jarvis@potatolondon.com","caveats":{"as":"did:key:z6MksF6gf2G5cM1F4Qf9KjoqmQNR5MC5AVNbbrrE7LYGaYG6"}} is invalid
  - Capability can not be (self) issued by 'did:key:z6MksF6gf2G5cM1F4Qf9KjoqmQNR5MC5AVNbbrrE7LYGaYG6'
  - Can not derive from prf:0 - bafyreieo2nbn4aimgdo3nddr7fwjf6f4p4tdd4cpqip6i5soyfsafnzvru because:
    - Expired on Fri Aug 19 2022 13:16:40 GMT+0000 (Coordinated Universal Time)
```
Looking at the error it seems like it has already expired?

Here's my full log:
```
➜  w3up id
✔ Loading id
✔ ID: did:key:z6MksF6gf2G5cM1F4Qf9KjoqmQNR5MC5AVNbbrrE7LYGaYG6
➜  w3up whoami
✖ Could not check identity, check w3up-failure.log
➜  w3up register josh.jarvis@potatolondon.com
✖ Error: Claimed capability {"can":"identity/register","with":"mailto:josh.jarvis@potatolondon.com","caveats":{"as":"did:key:z6MksF6gf2G5cM1F4Qf9KjoqmQNR5MC5AVNbbrrE7LYGaYG6"}} is invalid
  - Capability can not be (self) issued by 'did:key:z6MksF6gf2G5cM1F4Qf9KjoqmQNR5MC5AVNbbrrE7LYGaYG6'
  - Can not derive from prf:0 - bafyreieo2nbn4aimgdo3nddr7fwjf6f4p4tdd4cpqip6i5soyfsafnzvru because:
    - Expired on Fri Aug 19 2022 13:16:40 GMT+0000 (Coordinated Universal Time)
```

Let me know if this is simply something I've misunderstood, or a prerequisite I have missed.
Thanks!

**Comment by joshJarr** [comment]
Quick update: tried this again with the lastest release (commit [87cba8d](https://github.com/nftstorage/w3up-cli/commit/87cba8d661cbf384a65f93d540898839d7897060)) and encountered the same problem.

The result of `w3up-failure.log` is:
```
whoami: {}
```

**Comment by ice-breaker-tg** [comment]
This is a known issue and we are looking into it.
Thanks for the detailed info.

**Comment by ice-breaker-tg** [comment]
@joshJarr as a clarifying question for this, are you on a mac?

**Comment by joshJarr** [comment]
Yes I was (sorry for the delay in getting back to you!

**Comment by JeffLowe** [comment]
Based on current usage, this appears to be resolved.
