### ISSUE TITLE
CLI:  list CAR CIDS uploaded when upload split into multiple CAR files.

### ISSUE THREAD

**Issue by ice-breaker-tg** [web3-storage/w3up-cli#30]
This would be a list of CIDs uploaded via cli.

This would allow user to use this to push a list of CIDs to link/re-link.

**Comment by JeffLowe** [comment]
This is related to the stickiness of data

**Comment by ice-breaker-tg** [comment]
First pass on this shows the CID of the CAR as well as any root CIDs in the car (given that we generated it).

**Comment by the-simian** [comment]
Update: we've handled all the account-linking related stuff (stickiness) this is related to max-file-size and car chunking atm

**Comment by the-simian** [comment]
To be clear, this is not the same as listing all the *root* CIDS (which also need to happen) this is about listing all the CAR chunks in an upload. the other issue is here: https://github.com/nftstorage/w3up-cli/issues/32
