### ISSUE TITLE
show root CID in upload / list output

### ISSUE THREAD

**Issue by yusefnapora** [web3-storage/w3up-cli#32]
Hey hey, just got registered and have started playing with this a bit.

Currently the `w3up upload` output shows the CID of the uploaded CAR, but not the root CID of the dag inside the CAR:

```
✔ Succeeded uploading bagbaierawzqhbxot7mglim4hhg35w3yz47kts6ma3ld3elai77eaypgnhpgq with 200: OK
```

To make it easy to retrieve the content it would be great to show the root CID. Showing a gateway URL would be great too, for easy copy/paste to check things in a browser.

**Comment by jchris** [comment]
related to #30

**Comment by ice-breaker-tg** [comment]
Oop, thought there was another issue for the list part of this.

**Comment by jchris** [comment]
I added a related issue for the service. It might be done already? https://github.com/web3-storage/w3up/issues/222
