### ISSUE TITLE
For upload session, associate all cars with same session account

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/w3up-cli#34]
Solve to avoid every CAR getting different UUID despite same content. (discussion[ here ](https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1660942938783889)) 
- On every upload generate new keypair -> session account DID.
- invoke account/link to associate session account with actual account https://github.com/web3-storage/ucanto/blob/w3/w3/store/src/identity/capability.js#L63-L70
- for every car in the upload do store/add for both accounts

**Comment by ice-breaker-tg** [comment]
closed in favor of web3-storage/ucan-protocol#54
