### ISSUE TITLE
DECISION - Determine w3up-cli readiness for Alpha Release

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/w3up-cli#36]
Determined in 8.19 meeting ( [notes](https://www.notion.so/CLI-Alpha-Release-Planning-902eb595f6fc43f49d26d1fd1b6d2d38#6b55c0c5b1f4406d85136d5b6dd1db09) ) we need to meet with all parties to determine alpha release readiness.

- [x] demo CLI in w3up team meeting, determine collective consensus on alpha readiness

Currently I feel like these items remain

- [x] [#30](https://github.com/web3-storage/w3up-cli/issues/30) 
- [ ] [#141 ](https://github.com/web3-storage/w3up/issues/141)
- [ ] [#50 ](https://github.com/web3-storage/w3up-cli/issues/50)
- [x] [#32 ](https://github.com/web3-storage/w3up-cli/issues/32)
- [x] [#42 ](https://github.com/web3-storage/w3up-cli/issues/42)
- [ ] [#57](https://github.com/web3-storage/w3up-cli/issues/57)

**Comment by jchris** [comment]
Let's focus on the issue marked [P1](https://github.com/nftstorage/w3up-cli/issues?q=is%3Aissue+is%3Aopen+label%3AP1) first, and then see what the delta for alpha is.

**Comment by the-simian** [comment]
Currently I feel like these items remain

- [ ] [#30](https://github.com/nftstorage/w3up-cli/issues/30) 
- [ ] [#141 ](https://github.com/nftstorage/w3up/issues/141)
- [ ] [#50 ](https://github.com/nftstorage/w3up-cli/issues/50)
- [ ] [#32 ](https://github.com/nftstorage/w3up-cli/issues/32)
- [ ] [#42 ](https://github.com/nftstorage/w3up-cli/issues/42)
- [ ] [#57](https://github.com/nftstorage/w3up-cli/issues/57)

**Comment by jchris** [comment]
I think we should plan to work on https://github.com/web3-storage/w3up-cli/issues/58 as soon as it wouldn't be a painful context switch (eg after the chunking)

**Comment by JeffLowe** [comment]
We are well beyond alpha into Beta, thus closing this out.
