### ISSUE TITLE
make validation email token expire less fast

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3up-cli#54]
I bet this is configured somewhere else, but testing the flow I was just not able to get through the click loop in time. (Distracted by a couple of messages on the way.)

```
jchris@MacBook-Pro-2 w3up-cli % w3up id                       
✔ Generating new id
✔ ID: did:key:z6MkouThLRmDHzeocmU6V9KegM8CDfc7P8TuxZfM1WBGb5t5
jchris@MacBook-Pro-2 w3up-cli % w3up register jchris@dag.house
✖ Error: Claimed capability {"can":"identity/register","with":"mailto:jchris@dag.house","caveats":{"as":"did:key:z6MkouThLRmDHzeocmU6V9KegM8CDfc7P8TuxZfM1WBGb5t5"}} is invalid
  - Capability can not be (self) issued by 'did:key:z6MkouThLRmDHzeocmU6V9KegM8CDfc7P8TuxZfM1WBGb5t5'
  - Can not derive from prf:0 - bafyreibb3lefh5ho42aj5z3x7mibv4qnodd75tmfyiu3vxttlmfxw64dae because:
    - Expired on Mon Aug 29 2022 14:21:29 GMT+0000 (Coordinated Universal Time)
```

**Comment by jchris** [comment]
also, where should I file an issue that the validation link just says "Done" when it's clicked?

**Comment by JeffLowe** [comment]
Just file it here and we can assign it out to whomever needs to address it.

**Comment by hugomrdias** [comment]
i already did this a few weeks ago ? lets define a number for this.

20mins ?

**Comment by ice-breaker-tg** [comment]
I don't know if anyone has seen this recently.

@jchris if you know if anyone has, we'll keep this open, otherwise, please let me know / close this if it seems fixed.
