### ISSUE TITLE
ability to delegate UCANs 

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3up-cli#58]
this might be able to leverage existing code from @Gozala or @hugomrdias

**Comment by JeffLowe** [comment]
Currently blocked:  awaiting writeup from Irakli.

**Comment by Gozala** [comment]
General idea is to have a `delegate` command along the lines of `w3up delegate did:key:zBob --can store/add --with did:key:zAccount` 

1. `with` is optional and should default to the account DID. In fact it will only be relevant when we have multiple accounts support.
2. `can` is required and should be possible to specify several capabilities.
3. `did:key:zBob` will correspond to audience in the UCANs

In terms of implementation, there is `delegate` function in ucanto that could be leveraged, here is the an example illustrating it https://github.com/web3-storage/ucanto/blob/main/packages/core/test/lib.spec.js#L337-L346

Idea would be to use `.export()` delegation and encode it into a CAR file. Then import exported delegation on the other device via `Delegation.import()` function see

https://github.com/web3-storage/ucanto/blob/37f1d660da9b9f6cbac03542700d641cc741ce0d/packages/core/test/lib.spec.js#L348

To import delegation we would need another command in the CLI, I maybe something like `w3up authorize delegation.car` (Can't think of better verb), which would need to:

1. Which would need to persist that delegation on device.
2. Client will need to include imported delegations in `proofs` field when creating invocations e.g. here https://github.com/web3-storage/w3up-client/blob/main/src/index.js#L192-L198
    - We could be bit smart about when to include which proofs or just include them blindly at first, if proofs aren't required they won't harm.


Please note: Right now CLI seems to use same DID for both account and agent which we'd want to change with new accounts thinking. We don't need to block this on that change, just need to make sure that when we introduce such change we delegate access to an account as opposed to agent.

**Comment by Gozala** [comment]
Delegator would also needs to store exported delegation locally, to retain ability of revoking delegated capabilities. Speaking of which we'd need `w3up revoke` command. So far we don't actually have revocation implemented on the backend so we can leave out revoke command, but we should still retain delegations so we could add this feature in the future.

We should also figure out how long delegations should be valid for & I don't know what is the reasonable default (do you have an opinion @jchris ?). And we probably need additional flag corresponding to [`lifetimeInSeconds`](https://github.com/ipld/js-dag-ucan/blob/main/src/lib.js#L140) to be able to provide a non-default

**Comment by the-simian** [comment]
@Gozala currently we do have a differnce between the agent and account, but I think there's some ambiguity in the cli's output so I opened: https://github.com/web3-storage/w3up-cli/issues/60

**Comment by Gozala** [comment]
> @Gozala currently we do have a differnce between the agent and account, but I think there's some ambiguity in the cli's output so I opened: #60

Thanks! Indeed, distinction between agents and agents developed afterward. I think there are some nuances here but I'll followup on those in #60

**Comment by jchris** [comment]
how close are we to being able to support `w3up delegate did:key:zBob --can store/add` ?

**Comment by JeffLowe** [comment]
Confirmed in writes meeting.  @ice-breaker-tg to finish this up and release (not waiting for UCAN 0.9).

**Comment by JeffLowe** [comment]
Delegation in cli with release of [w3up-cli v 1.6](https://github.com/web3-storage/w3up-cli/releases/tag/v1.6.0)
Further refinements to delegation in cli should be described in new tickets.
