### ISSUE TITLE
Specify account as well as agent in the whoami and id commands

### ISSUE THREAD

**Issue by the-simian** [web3-storage/w3up-cli#60]
currently it does:

this is the `account`
```sh
$ w3up whoami
√ did:ipld:bafyreihv7hw3zasimbirfrdnrcolpw4lyr6zbnpigcn...
```
and

this is the `agent`

```sh
$ w3up id
√ Loading id
√ ID: did:key:z6MkuJzmdv3JQU6zTAc5Fa7YfbhE2Gm2s......
```

This is causing some confusion, we need to specify the agent being used and the account the agent, both in whoami and with id you'd show one or both depending if you registered or not.

The same account on, say a different device would show a different agent, same account.

**Comment by Gozala** [comment]
I think it is also worth considering that you may have access to multiple accounts on a specific agent. Not only that you may have access to certain capability set for an account. So it may be worth considering how are we going to present all that.

What I'm recognizing here is that agent needs to:

1. Manage delegated capabilities in some persistent store
2. Should allow associating names to accounts (which could be roughly equivalent of git remotes)

**Comment by ice-breaker-tg** [comment]
This is partially covered by #83
