### ISSUE TITLE
Implement CARmanifest when CAR is created

### ISSUE THREAD

**Issue by JeffLowe** [web3-storage/w3up-cli#61]
At CAR creation, create CARmanifest, containing (all CARs created, JSON about the order).

**Comment by JeffLowe** [comment]
Will use graph based implementation.

**Comment by ice-breaker-tg** [comment]
This is pretty much not needed, as this is dealt with via rootcid association, and cardex generation.
May need a new ticket at some point for directory parsing in processor.
