### ISSUE TITLE
Clean up did:key did:ipld for the description/readme when running id and whoami

### ISSUE THREAD

**Issue by the-simian** [web3-storage/w3up-cli#78]
- [x] add the open command from https://github.com/web3-storage/w3up-cli/pull/76
- [x] readme does need to show the whoami command lists both agent/account ids now

- [x] make sure docs and examples show the right looking identifier, they look like this now:

```
$ w3up whoami
√ did:ipld:bafyrei...

$ w3up id
√ Loading id
√ ID: did:key:z6Mk...
```

**Comment by the-simian** [comment]
(also should fix the install command while in there too, point to: https://www.npmjs.com/package/@web3-storage/w3up-cli)

**Comment by ice-breaker-tg** [comment]
> (also should fix the install command while in there too, point to: https://www.npmjs.com/package/@web3-storage/w3up-cli)

This is already corrected, the readme does need to show the whoami command lists both agent/account ids now.

**Comment by the-simian** [comment]
Also need to add the `open` command from #76

**Comment by JeffLowe** [comment]
I believe remaining tasks on this are now documented in the task description.
