### ISSUE TITLE
directory sharding

### ISSUE THREAD

**Issue by jchris** [web3-storage/w3up-cli#79]
**Is your feature request related to a problem? Please describe.**
If we don't have directory sharding, we can fail on uploads of long directory listings.

**Describe the solution you'd like**
I heard @Gozala say this needs to be implemented in unixfs?

**Describe alternatives you've considered**
I think we haven't hit this in real life yet as an issue.

**Additional context**

**Comment by ice-breaker-tg** [comment]
This should not be an issue as it currently will shard directories and files or any blocks across cars when splitting is enabled.
